### ISSUE TITLE
Checkstyle error on windows

### ISSUE THREAD

**Issue by Vatavuk** [driver733/VK-Uploader#384]
I've got this checkstyle error while executing `mvn clean test -DskipTests=true qulice:check` on windows machine.

```
Checkstyle: C:\workspace\sq_awards\VK_tmp\VK-Uploader\src\test\java\com\driver733\vkuploader\wallpost\attachment\message\MessageWithRandomQuoteTest.java[52]: Line is longer than 80 characters (found 86). (LineLengthCheck)
```

I have no problems when executing on OSX

**Comment by driver733** [comment]
Fixed in https://github.com/driver733/VK-Uploader/runs/716132425?check_suite_focus=true
